import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';

/// Firestore settings used app-wide to enable offline-first persistence:
/// cached reads and queued writes work while the device has no network
/// connection.
///
/// Extracted as a standalone constant (rather than only inlined inside
/// [bootstrapFirebase]) so it can be unit tested without a live Firebase
/// app or platform channels.
const Settings firestorePersistenceSettings = Settings(
  persistenceEnabled: true,
);

/// Initializes Firebase for the current platform and configures Firestore
/// for offline-first persistence.
///
/// [options] must be supplied by the caller — normally
/// `DefaultFirebaseOptions.currentPlatform` from the `firebase_options.dart`
/// generated by `flutterfire configure`. That generated file does not exist
/// yet in this repo (it's produced by a manual, deferred setup step), so
/// this module intentionally has no compile-time dependency on it. Wiring
/// the real options is left to the app-shell entrypoint.
Future<void> bootstrapFirebase({required FirebaseOptions options}) async {
  await Firebase.initializeApp(options: options);
  FirebaseFirestore.instance.settings = firestorePersistenceSettings;
}
